name = "PonteAI"
uuid = "fb4e84c6-5602-419f-9880-a9ccb2e98681"
authors = ["Federico Poloni"]
version = "1.0.0-DEV"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
